repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      require_serial: true
      types: [python]
      stages:
        - commit


    - id: ruff
      name: ruff
      entry: ruff --fix
      language: system
      types: [python]
      stages:
        - commit

    - id: pyright
      name: pyright
      entry: pyright
      language: system
      types: [python]
      stages:
        - commit
