[tool.black]
line-length = 120
exclude = '''
(
    venv*
  | \.*
  | __pycache__
  | Dockerfile
  | env/
)
'''
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 120
force_grid_wrap = 0
multi_line_output = 3
include_trailing_comma = true
