agent:
  discount_factor: 0.99
  exploration:
    decay_steps: 40_000
    epsilon_init: 1
    epsilon_min: 0.1
  optimizer:
    name: AdamW
    lr: 1e-4
    decay_steps: 400_000
    warmup_steps: 10000
  loss: 'mse'

  model:
    hidden_dim: 128
    n_layers: 1
  type: dqn
replay_buffer_size: 10_000
seed: 1
training:
  batch_size: 128
  log_every: 30
  n_steps: 400_000
  n_val_states: 10000
  val_every: 1000